hero:
  text: Headline for our services hero image
  image: assets/hero1.png

services:
  - title: Service 1C
    description: Some info about service 1

  - title: Service 2s
  - description: Some info about service 2bszz

